export const rentHouses = [
  {
    id: 1,
    type: "featured",
    mainImage: "/Rent-houses/House-1/home1-1.jpg",
    moreImages: [
      "/Rent-houses/House-1/home1-2.jpg",
      "/Rent-houses/House-1/home1-3.jpg",
      "/Rent-houses/House-1/home1-4.jpg",
      "/Rent-houses/House-1/home1-5.jpg",
    ],
    name: "Nairobi",
    address: "Nairobi,kenya",
    details: [
      "4 Bedrooms",
      "3 attached Bathrooms",
      "2 common Bathrooms",
      "2 Kitchens",
      "Beautifully designed structure",
      "Unfurnished",
      "Best Location",
      "Area: Limuru road",
    ],
    description:
      "DHA 9 Housing Scheme A block 10 Marla New brand house available for sale Good location house near by hospital and market and masjid and LGS school and other facilities",
  },
  {
    id: 2,
    type: "featured",
    mainImage: "/Rent-houses/House-2/home2-1.jpg",
    moreImages: [
      "/Rent-houses/House-2/home2-2.jpg",
      "/Rent-houses/House-2/home2-3.jpg",
      "/Rent-houses/House-2/home2-4.jpg",
      "/Rent-houses/House-2/home2-5.jpg",
    ],
    name: "Tigoni",
    address: "Limuru, Tigoni",
    details: [
      "4 Bedrooms",
      "1 big launge",
      "4 attached Bathrooms",
      "1 common Bathroom",
      "2 Kitchens",
      "Beautiful garden with parking",
      "Half-furnished",
      "Area: tigoni",
    ],
    description:
      "Tigoni Town 20 Marla New brand house available for sale Good location house near by hospital and market and masjid and school, park and other facilities in fully future developed society",
  },
  {
    id: 3,
    type: "Featured",
    mainImage: "/Rent-houses/House-3/home3-1.jpg",
    moreImages: [
      "/Rent-houses/House-3/home3-2.jpg",
      "/Rent-houses/House-3/home3-3.jpg",
      "/Rent-houses/House-3/home3-4.jpg",
      "/Rent-houses/House-3/home3-5.jpg",
    ],
    name: "Eldoret",
    address: "Eldoret",
    details: [
      " Block 7",
      "Kule PLAZA",
      "2 Bedrooms",
      "2 Bathrooms",
      "American design kitchen",
      "Floor Level: 1st floor",
      "Unfurnished",
      "Area: 950 sqr.feet",
    ],
    description:
      "Apartment in installment (View phone number) Sqfeet VIP location near to park nairobi. You can find a Flat on the lower or upper levels, as suiting to your requirement. Buying property is a one-time life decision and we can help you with it. 950 Square Feet sized residential or commercial property is best for investment purposes. All your queries concerned with this property are welcome, so please contact us.",
  },
  {
    id: 4,
    type: "Featured",
    mainImage: "/Rent-houses/House-4/home4-1.jpg",
    moreImages: [
      "/Rent-houses/House-4/home4-2.jpg",
      "/Rent-houses/House-4/home4-3.jpg",
      "/Rent-houses/House-4/home4-4.jpg",
      "/Rent-houses/House-4/home4-5.jpg",
    ],
    name: "Machakos",
    address: "Blue Area, F-3, nairobi",
    details: [
      "Location: Machakos",
      "2 Bedrooms",
      "Drawing Room",
      "2 Bathrooms",
      "2 Modern kitchens",
      "Floor Level: 1st floor",
      "Unfurnished",
      "Area: 1,100 sqr.feet",
    ],
    description:
      "The Flat is well designed to accommodate the family and their guests. When it comes to housing, location is everything and we have quite a many options regarding that. The perfect 1,1000 Square Feet listing for your property needs are right within your reach.",
  },
  {
    id: 5,
    type: "Featured",
    mainImage: "/Rent-houses/House-5/home5-1.jpg",
    moreImages: [
      "/Rent-houses/House-5/home5-2.jpg",
      "/Rent-houses/House-5/home5-3.jpg",
      "/Rent-houses/House-5/home5-4.jpg",
      "/Rent-houses/House-5/home5-5.jpg",
    ],
    name: "Thika",
    address: "Thika",
    details: [
      "Bunglow at thika town scheme",
      "4 Bedrooms",
      "A big drawing Room",
      "5 Bathrooms",
      "2 Modern style kitchens",
      "Unfurnished",
      "Car Parking",
      "Area: 120 sqr.yards",
    ],
    description:
      "Thika town Brand New Project Banglow Double Story 120 Sq Yards Bedrooms with attach baths Drawing Lounge open American Kitchen Washing area Huge Terrace Tiles Flooring Fancy lights Complete Boundary wall project Daily Sweet line Water No Load Shedding gas Security Guards Masjid Park Pure Family Environment Main Road approach Ideal Location",
  },
  {
    id: 6,
    type: "featured",
    mainImage: "/Rent-houses/House-6/home6-1.jpg",
    moreImages: [
      "/Rent-houses/House-6/home6-2.jpg",
      "/Rent-houses/House-6/home6-3.jpg",
      "/Rent-houses/House-6/home6-4.jpg",
      "/Rent-houses/House-6/home6-5.jpg",
    ],
    name: "Kitengela",
    address: "Kitengela",
    details: [
      "Kitengela",
      "5 Bedrooms",
      "Big drawing Room Lounge",
      "6 Bathrooms",
      "3 Modern style kitchens",
      "Unfurnished",
      "Indoor Car Parking",
      "Area: 120 sqr.yards",
    ],
    description:
      "The Best Design As Per Your Desire And Your Dream House a WiringGrandPump Feel Free To Contact For Further Details",
  },
];
